// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package taskpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Completed            bool     `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type GetTaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTaskResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Task    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskResponse) Reset()         { *m = GetTaskResponse{} }
func (m *GetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskResponse) ProtoMessage()    {}
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *GetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResponse.Unmarshal(m, b)
}
func (m *GetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResponse.Merge(m, src)
}
func (m *GetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskResponse.Size(m)
}
func (m *GetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResponse proto.InternalMessageInfo

func (m *GetTaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GetTaskResponse) GetData() *Task {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type AddTaskResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Task    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

func (m *AddTaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *AddTaskResponse) GetData() *Task {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Task    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UpdateTaskResponse) GetData() *Task {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type DeleteTaskResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResponse) Reset()         { *m = DeleteTaskResponse{} }
func (m *DeleteTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResponse) ProtoMessage()    {}
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *DeleteTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResponse.Unmarshal(m, b)
}
func (m *DeleteTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResponse.Merge(m, src)
}
func (m *DeleteTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResponse.Size(m)
}
func (m *DeleteTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResponse proto.InternalMessageInfo

func (m *DeleteTaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type GetTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksRequest) Reset()         { *m = GetTasksRequest{} }
func (m *GetTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksRequest) ProtoMessage()    {}
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *GetTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksRequest.Unmarshal(m, b)
}
func (m *GetTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksRequest.Merge(m, src)
}
func (m *GetTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksRequest.Size(m)
}
func (m *GetTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksRequest proto.InternalMessageInfo

type GetTasksResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Task    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksResponse) Reset()         { *m = GetTasksResponse{} }
func (m *GetTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse) ProtoMessage()    {}
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{10}
}

func (m *GetTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse.Unmarshal(m, b)
}
func (m *GetTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse.Marshal(b, m, deterministic)
}
func (m *GetTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse.Merge(m, src)
}
func (m *GetTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse.Size(m)
}
func (m *GetTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse proto.InternalMessageInfo

func (m *GetTasksResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GetTasksResponse) GetData() *Task {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddBatchTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBatchTaskRequest) Reset()         { *m = AddBatchTaskRequest{} }
func (m *AddBatchTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddBatchTaskRequest) ProtoMessage()    {}
func (*AddBatchTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{11}
}

func (m *AddBatchTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBatchTaskRequest.Unmarshal(m, b)
}
func (m *AddBatchTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBatchTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddBatchTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBatchTaskRequest.Merge(m, src)
}
func (m *AddBatchTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddBatchTaskRequest.Size(m)
}
func (m *AddBatchTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBatchTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBatchTaskRequest proto.InternalMessageInfo

func (m *AddBatchTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type AddBatchTaskResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBatchTaskResponse) Reset()         { *m = AddBatchTaskResponse{} }
func (m *AddBatchTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddBatchTaskResponse) ProtoMessage()    {}
func (*AddBatchTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{12}
}

func (m *AddBatchTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBatchTaskResponse.Unmarshal(m, b)
}
func (m *AddBatchTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBatchTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddBatchTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBatchTaskResponse.Merge(m, src)
}
func (m *AddBatchTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddBatchTaskResponse.Size(m)
}
func (m *AddBatchTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBatchTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBatchTaskResponse proto.InternalMessageInfo

func (m *AddBatchTaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *AddBatchTaskResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*GetTaskRequest)(nil), "task.GetTaskRequest")
	proto.RegisterType((*GetTaskResponse)(nil), "task.GetTaskResponse")
	proto.RegisterType((*AddTaskRequest)(nil), "task.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "task.AddTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "task.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "task.UpdateTaskResponse")
	proto.RegisterType((*DeleteTaskRequest)(nil), "task.DeleteTaskRequest")
	proto.RegisterType((*DeleteTaskResponse)(nil), "task.DeleteTaskResponse")
	proto.RegisterType((*GetTasksRequest)(nil), "task.GetTasksRequest")
	proto.RegisterType((*GetTasksResponse)(nil), "task.GetTasksResponse")
	proto.RegisterType((*AddBatchTaskRequest)(nil), "task.AddBatchTaskRequest")
	proto.RegisterType((*AddBatchTaskResponse)(nil), "task.AddBatchTaskResponse")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0xef, 0xd2, 0x40,
	0x10, 0xa5, 0xfc, 0x2a, 0x94, 0xc1, 0x80, 0x8c, 0x08, 0xb5, 0x31, 0xa4, 0xd9, 0x13, 0x07, 0x42,
	0x08, 0xc4, 0xc4, 0x8b, 0x07, 0x88, 0x89, 0xd6, 0x78, 0xaa, 0x7a, 0xf1, 0x62, 0x96, 0xee, 0x46,
	0x1b, 0xfe, 0xb4, 0xb2, 0x8b, 0xdf, 0xc3, 0x6f, 0x6c, 0xba, 0xed, 0xf6, 0xaf, 0xf1, 0x17, 0xc2,
	0xad, 0x33, 0x3b, 0x6f, 0xde, 0xcc, 0xbc, 0x97, 0x02, 0x48, 0x2a, 0x0e, 0xcb, 0xf8, 0x12, 0xc9,
	0x08, 0xcd, 0xe4, 0x9b, 0x1c, 0xc1, 0xfc, 0x42, 0xc5, 0x01, 0x07, 0xd0, 0x0e, 0x99, 0x6d, 0xb8,
	0xc6, 0xbc, 0xe7, 0xb7, 0x43, 0x86, 0x63, 0x78, 0x22, 0x43, 0x79, 0xe4, 0x76, 0x5b, 0xa5, 0xd2,
	0x00, 0x5d, 0xe8, 0x33, 0x2e, 0x82, 0x4b, 0x18, 0xcb, 0x30, 0x3a, 0xdb, 0x0f, 0xea, 0xad, 0x9c,
	0xc2, 0x57, 0xd0, 0x0b, 0xa2, 0x53, 0x7c, 0xe4, 0x92, 0x33, 0xdb, 0x74, 0x8d, 0xb9, 0xe5, 0x17,
	0x09, 0xe2, 0xc2, 0xe0, 0x3d, 0x97, 0x09, 0xa1, 0xcf, 0x7f, 0x5d, 0xb9, 0x90, 0x75, 0x5e, 0xe2,
	0xc1, 0x30, 0xaf, 0x10, 0x71, 0x74, 0x16, 0x1c, 0x27, 0xd0, 0x11, 0x92, 0xca, 0xab, 0x50, 0x65,
	0x96, 0x9f, 0x45, 0x38, 0x03, 0x93, 0x51, 0x49, 0xd5, 0x84, 0xfd, 0x35, 0x2c, 0xd5, 0x6e, 0x0a,
	0xa9, 0xf2, 0x64, 0x05, 0x83, 0x2d, 0x63, 0x65, 0xb2, 0x19, 0xa8, 0xa5, 0x55, 0x9f, 0x1a, 0x42,
	0x1d, 0xc3, 0x83, 0x61, 0x8e, 0xb8, 0x93, 0x7c, 0x03, 0xa3, 0xaf, 0x31, 0xa3, 0x92, 0xdf, 0xc2,
	0xff, 0x09, 0xb0, 0x0c, 0xba, 0x73, 0x84, 0x05, 0x8c, 0xde, 0xf1, 0xe4, 0xee, 0xe5, 0x11, 0xa6,
	0xd0, 0x4d, 0xea, 0xbe, 0xe7, 0x47, 0xef, 0x24, 0xa1, 0xc7, 0xc8, 0x02, 0xb0, 0x5c, 0xfd, 0x7f,
	0x6e, 0x32, 0xca, 0x65, 0x12, 0x59, 0x67, 0xf2, 0x11, 0x9e, 0x15, 0xa9, 0x3b, 0x47, 0x7f, 0x0d,
	0xcf, 0xb7, 0x8c, 0xed, 0xa8, 0x0c, 0x7e, 0xde, 0x72, 0xbf, 0x0f, 0x30, 0xae, 0xc2, 0x1e, 0x19,
	0xc3, 0x86, 0xee, 0x89, 0x0b, 0x41, 0x7f, 0x68, 0x9b, 0xeb, 0x70, 0xfd, 0xe7, 0x01, 0xfa, 0x49,
	0x8b, 0xcf, 0xfc, 0xf2, 0x3b, 0x0c, 0x38, 0xbe, 0x81, 0x6e, 0xb6, 0x1c, 0x8e, 0x53, 0xda, 0xaa,
	0x8f, 0x9d, 0x17, 0xb5, 0x6c, 0xca, 0x4c, 0x5a, 0x09, 0x32, 0xf3, 0x94, 0x46, 0x56, 0x4d, 0xa9,
	0x91, 0x35, 0xe3, 0x91, 0x16, 0x6e, 0x01, 0x0a, 0x37, 0xe0, 0x34, 0x2d, 0x6b, 0x98, 0xca, 0xb1,
	0x9b, 0x0f, 0xe5, 0x16, 0x85, 0xa8, 0xba, 0x45, 0xc3, 0x14, 0xba, 0x45, 0x53, 0x7f, 0xd2, 0xc2,
	0xb7, 0x60, 0x69, 0x59, 0xb1, 0xba, 0xa4, 0x56, 0xde, 0x99, 0xd4, 0xd3, 0x1a, 0xbc, 0x32, 0xd0,
	0x83, 0xa7, 0x65, 0x49, 0xf0, 0x65, 0xbe, 0x6d, 0x5d, 0x5d, 0xc7, 0xf9, 0xd7, 0x93, 0x6e, 0x35,
	0x37, 0x76, 0xd6, 0x37, 0xe5, 0xd5, 0x78, 0xbf, 0xef, 0xa8, 0x3f, 0xd8, 0xe6, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0xf8, 0xd1, 0xe1, 0xcf, 0x04, 0x00, 0x00,
}
